server:
  port: 9011

spring:
  application:
    name: my-xhs-order
  datasource:
    url: jdbc:mysql://localhost:13306/my_xhs_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "Xhs@2026#MySQL"
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848
      config:
        server-addr: localhost:18848
        file-extension: yaml