port 26379
sentinel announce-ip ${HOST_IP}
sentinel monitor mymaster ${HOST_IP} 6379 1
sentinel auth-pass mymaster Xhs@2026#Redis
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 30000
sentinel parallel-syncs mymaster 1
