{
 "title": "JVM 监控",
 "tags": [
  "myxhs",
  "jvm"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, application)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM 内存使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=~\"$application\"}",
     "legendFormat": "{{instance}} - {{area}}"
    }
   ]
  },
  {
   "title": "JVM GC 暂停时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum{application=~\"$application\"}",
     "legendFormat": "{{instance}} - {{cause}}"
    }
   ]
  },
  {
   "title": "JVM 线程数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=~\"$application\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=~\"$application\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}