brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 跨机器部署：brokerIP1 必须是服务器对外IP
namesrvAddr = 127.0.0.1:9876
brokerIP1 = 21.91.124.110
listenPort = 11911

# 存储路径
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog

# 开发环境自动创建 Topic
autoCreateTopicEnable = true
