#################################################
## ???? ? ?? my_xhs_content.t_note ?
#################################################

# MySQL ????
canal.instance.master.address = 127.0.0.1:13306
canal.instance.dbUsername = canal
canal.instance.dbPassword = Canal@2026#Sync
canal.instance.connectionCharset = UTF-8

# ???????????
# ??? my_xhs_content ?? t_note ?
canal.instance.filter.regex = my_xhs_content\\.t_note

# ??????????
canal.instance.filter.black.regex =

# Canal Server ID??? MySQL Slave???? MySQL server-id ???
canal.instance.mysql.slaveId = 1001

# MQ Topic??????? Topic?
canal.mq.topic = NOTE_INDEX_TOPIC

# ??????????????
canal.mq.partition = 0
