input {
  file {
    path => "/logs/*.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  # 提取服务名
  grok {
    match => { "[log][file][path]" => "/logs/(?<service>[^/]+)\.json" }
  }
  # 时间戳处理
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:19200"]
    user => "elastic"
    password => "Xhs@2026#Elastic"
    index => "myxhs-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
