#################################################
## ???? ? ?? my_xhs_product.t_spu ?
#################################################

# MySQL ????
canal.instance.master.address = 127.0.0.1:13306
canal.instance.dbUsername = canal
canal.instance.dbPassword = Canal@2026#Sync
canal.instance.connectionCharset = UTF-8

# ???????????
# ?? my_xhs_product ?? t_spu ? t_sku ?
canal.instance.filter.regex = my_xhs_product\\.t_spu,my_xhs_product\\.t_sku

# ???
canal.instance.filter.black.regex =

# Canal Server ID?????????????? MySQL server-id ???
canal.instance.mysql.slaveId = 1002

# MQ Topic
canal.mq.topic = PRODUCT_INDEX_TOPIC

# ????
canal.mq.partition = 0
