# ==========================================
# MyXHS Redis Sentinel-3 配置
# 端口：26381
# ==========================================

port 26381

sentinel monitor mymaster 127.0.0.1 16379 2
sentinel auth-pass mymaster Xhs@2026#Redis

sentinel monitor mymaster-cache 127.0.0.1 16380 2
sentinel auth-pass mymaster-cache Xhs@2026#Redis

sentinel monitor mymaster-business 127.0.0.1 16381 2
sentinel auth-pass mymaster-business Xhs@2026#Redis

sentinel down-after-milliseconds mymaster 5000
sentinel down-after-milliseconds mymaster-cache 5000
sentinel down-after-milliseconds mymaster-business 5000

sentinel failover-timeout mymaster 30000
sentinel failover-timeout mymaster-cache 30000
sentinel failover-timeout mymaster-business 30000

sentinel parallel-syncs mymaster 1
sentinel parallel-syncs mymaster-cache 1
sentinel parallel-syncs mymaster-business 1
